version: '2.1'

orbs:
  node: circleci/node@5.0.2


jobs:
  deploy-surge:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13.1'
      - node/install-packages
      - run: npm run start &
      - run:
          name: smoke-test-site
          command: |
            for NUMBER_TRY in {1..60}
            do
              RESPONSE=$(wget --spider --server-response http://localhost:3000/ 2>&1 | grep -c '200\ OK')

              if [[RESPONSE == 1]]
              then
                  exit 0
              fi

              sleep 1
            done

            exit 1

      - run:
          name: build-for-deployment
          command: npm run build
      - run:
          name: deployment-production
          command: |
            npm install --global surge
            surge --project ./build --domain uncovered-brake.surge.sh



workflows:
  test-and-deploy:
    jobs:
      - deploy-surge
