version: '2.1'

orbs:
  node: circleci/node@5.0.2


jobs:
  smoke-test:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13.1'
      - node/install-packages
      - run:
          name: smoke-test-site
          command: |
            npm run start &

            ./scripts/smoke-test.sh

  deploy-surge:
    executor: node/default
    steps:
      - checkout
      - node/install:
            node-version: '16.13.1'
      - node/install-packages
      - run:
          name: build-for-deployment
          command: npm run build
      - run:
          name: deployment-production
          command: |
            npm install --global surge
            surge --project ./build --domain uncovered-brake.surge.sh

  validate-image-docker:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: get dive
          command: wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
      - run:
          name: install dive
          commando: sudo apt install ./dive_0.9.2_linux_amd64.deb
      - run:
          name: build and analyze image
          command: dive build -t delissgt/react-selenium-real-example:latest .



workflows:
  test-and-deploy:
    jobs:
      - deploy-surge:
          filters:
            branches:
              only: master
          requires:
            - smoke-test
      - smoke-test:
          requires:
            - validate-image-docker
      - validate-image-docker
