version: '2.1'

orbs:
  node: circleci/node@5.0.2


jobs:
  deploy-surge:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13.1'
      - node/install-packages
      - run:
          name: smoke-test-site
          command: |
            npm run start &

            ./scripts/smoke-test.sh

      - run:
          name: build-for-deployment
          command: npm run build
      - run:
          name: deployment-production
          command: |
            npm install --global surge
            surge --project ./build --domain uncovered-brake.surge.sh



workflows:
  test-and-deploy:
    jobs:
      - deploy-surge
